version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build: 
    jobs:
      - build-38
      - build-27

jobs:
  build-38:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: venv-38-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            python3 -m venv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install wheel
            pip install -r requirements.txt
            pylint pdk_client
            bandit -r .      
      - save_cache:
          key: venv-38-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app

  build-27:
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - restore_cache:
          key: venv-27-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Build and validate
          command: |
            virtualenv /home/circleci/venv
            . /home/circleci/venv/bin/activate
            pip install wheel
            pip install -r requirements.txt
            pylint pdk_client
            bandit -r .      
      - save_cache:
          key: venv-27-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "/home/circleci/venv"
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-reports/
          destination: python_app

